export const FETCH_QUESTIONS_REQUESTED = "FETCH_QUESTIONS_REQUESTED";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";
